### ISSUE TITLE
Failures with dev testthat

### ISSUE THREAD

**Issue by hadley** [MansMeg/markmyassignment#105]
I see the following failures when running R CMD check on markmyassignment with the dev version of testthat:

```
Loading required package: markmyassignment
-- ERROR (???): mark_my_assignment() -------------------------------------------
Error: Test failures
Backtrace:
    █
 1. └─markmyassignment::mark_my_assignment()
 2.   └─markmyassignment:::run_test_suite(...)
 3.     └─testthat::test_dir(...)
 4.       └─testthat:::test_files(...)
 5.         └─testthat:::test_files(...)
 6.           └─testthat:::test_files_check(...)

-- FAILURE (test-mark_my_dir.R:11:3): mark_my_dir() ----------------------------
res_mark[[1]] inherits from `character` not `testthat_results`.

-- ERROR (???): additional tests -----------------------------------------------
Error: Test failures
Backtrace:
    █
 1. └─markmyassignment::mark_my_assignment()
 2.   └─markmyassignment:::run_test_suite(...)
 3.     └─testthat::test_dir(...)
 4.       └─testthat:::test_files(...)
 5.         └─testthat:::test_files(...)
 6.           └─testthat:::test_files_check(...)

══ testthat results  ═══════════════════════════════════════════════════════════
ERROR (???): mark_my_assignment()
FAILURE (test-mark_my_dir.R:11:3): mark_my_dir()
ERROR (???): additional tests
```

Would you mind take a bit of a look to see what's wrong, and letting me know if you think it's a bug in testthat?

**Comment by MansMeg** [comment]
Thanks!

Ill look into this asap!

With kind regards,
Måns

======================
Måns Magnusson
+ 46 (0) 70 588 97 15
www.mansmagnusson.com
mons.magnusson@gmail.com
======================

**Comment by MansMeg** [comment]
Hi!

I have now taken a look at this and can reproduce your error. The error seems to come from different behaviors in how testthat returns results when running testthat within other functions.

What fails with the dev version is the following unit test (line 32 here: https://github.com/MansMeg/markmyassignment/blob/master/tests/testthat/test-mark_my_assignment.R):
```
expect_silent(x <- capture.output(y <- mark_my_assignment()))
```

The function `mark_my_assignment()` runs testthat under the hood and the function returns a `testthat_result` object and prints the result. The unit test checks this.

In the current CRAN release, this passes and everything works well, and this test pass.

In the dev version of testhat the same function seem to also return a testhat failure, in addition to the testthat_results. I.e. the 

```
> expect_silent(x <- capture.output(y <- mark_my_assignment()))
 Error: Test failures 
```

I'm not sure if this is a new intentional behavior?

**Comment by hadley** [comment]
Is it possible that you're calling `test_dir()`?

* `test_dir()` now defaults `stop_on_failure` to `TRUE` for consistency with
  other `test_` functions. The `wrap` argument has been deprecated; it's not
  clear that it should ever have been exposed.

**Comment by MansMeg** [comment]
Ok. Yes, thats very likely the problem. Will look into it tomorrow.

If I understand you right, I will just change stop_on_failure=FALSE in test_dir()?

**Comment by hadley** [comment]
Correct 😄

**Comment by MansMeg** [comment]
Its now fixed and a new vrsion is on its way to CRAN.
